-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- CODE Table Create SQL
CREATE TABLE CODE
(
    SEQ                NUMBER          NOT NULL, 
    NAME               VARCHAR2(30)    NOT NULL, 
    CREATE_USERID      VARCHAR2(20)    NOT NULL, 
    CREATE_DATETIME    DATE            DEFAULT SYSDATE NOT NULL, 
    UPDATE_USERID      VARCHAR2(20)    NOT NULL, 
    UPDATE_DATETIME    DATE            DEFAULT SYSDATE NOT NULL, 
    DELETE_FLAG        CHAR(1)         DEFAULT 'N' NOT NULL, 
    CONSTRAINT CODE_PK PRIMARY KEY (SEQ)
)
/

CREATE SEQUENCE CODE_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER CODE_AI_TRG
BEFORE INSERT ON CODE 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT CODE_SEQ.NEXTVAL
    INTO :NEW.SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER CODE_AI_TRG;
/

--DROP SEQUENCE CODE_SEQ;
/

COMMENT ON TABLE CODE IS '코드'
/

COMMENT ON COLUMN CODE.SEQ IS 'CODE MASTER'
/

COMMENT ON COLUMN CODE.NAME IS '코드 명'
/

COMMENT ON COLUMN CODE.CREATE_USERID IS '작성자'
/

COMMENT ON COLUMN CODE.CREATE_DATETIME IS '작성시간'
/

COMMENT ON COLUMN CODE.UPDATE_USERID IS '수정자'
/

COMMENT ON COLUMN CODE.UPDATE_DATETIME IS '수정시간'
/

COMMENT ON COLUMN CODE.DELETE_FLAG IS '삭제여부'
/


-- CODE Table Create SQL
CREATE TABLE BOARD
(
    SEQ                NUMBER           NOT NULL, 
    CATEGORY           CHAR(1)          NOT NULL, 
    TITLE              VARCHAR2(30)     NOT NULL, 
    CONTENT            CLOB             NOT NULL, 
    PHONE              VARCHAR2(30)     NULL, 
    PLACE              VARCHAR2(50)     NOT NULL, 
    B_TIME             DATE             NOT NULL, 
    B_STATE            VARCHAR2(50)     NULL, 
    B_FILE             VARCHAR2(200)    NULL, 
    HIT_CNT            NUMBER           DEFAULT 0 NOT NULL, 
    CREATE_USERID      VARCHAR2(20)     NOT NULL, 
    CREATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    UPDATE_USERID      VARCHAR2(20)     NOT NULL, 
    UPDATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    DELETE_FLAG        CHAR(1)          DEFAULT 'N' NOT NULL, 
    CONSTRAINT BOARD_PK PRIMARY KEY (SEQ)
)
/

CREATE SEQUENCE BOARD_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER BOARD_AI_TRG
BEFORE INSERT ON BOARD 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT BOARD_SEQ.NEXTVAL
    INTO :NEW.SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER BOARD_AI_TRG;
/

--DROP SEQUENCE BOARD_SEQ;
/

COMMENT ON TABLE BOARD IS '게시글'
/

COMMENT ON COLUMN BOARD.SEQ IS '글번호'
/

COMMENT ON COLUMN BOARD.CATEGORY IS '1. NOTICE, 2.LOST, 3.FIND'
/

COMMENT ON COLUMN BOARD.TITLE IS '제목'
/

COMMENT ON COLUMN BOARD.CONTENT IS '내용'
/

COMMENT ON COLUMN BOARD.PHONE IS '연락처'
/

COMMENT ON COLUMN BOARD.PLACE IS '장소'
/

COMMENT ON COLUMN BOARD.B_TIME IS '시간'
/

COMMENT ON COLUMN BOARD.B_STATE IS '현재 상태'
/

COMMENT ON COLUMN BOARD.B_FILE IS '첨부파일'
/

COMMENT ON COLUMN BOARD.HIT_CNT IS '조회수'
/

COMMENT ON COLUMN BOARD.CREATE_USERID IS '작성자'
/

COMMENT ON COLUMN BOARD.CREATE_DATETIME IS '작성시간'
/

COMMENT ON COLUMN BOARD.UPDATE_USERID IS '수정자'
/

COMMENT ON COLUMN BOARD.UPDATE_DATETIME IS '수정시간'
/

COMMENT ON COLUMN BOARD.DELETE_FLAG IS '삭제여부'
/


-- CODE Table Create SQL
CREATE TABLE CODE_ITEM
(
    SEQ                NUMBER          NOT NULL, 
    CODE_SEQ           NUMBER          NOT NULL, 
    NAME               VARCHAR2(30)    NOT NULL, 
    CREATE_USERID      VARCHAR2(20)    NOT NULL, 
    CREATE_DATETIME    DATE            DEFAULT SYSDATE NOT NULL, 
    UPDATE_USERID      VARCHAR2(20)    NOT NULL, 
    UPDATE_DATETIME    DATE            DEFAULT SYSDATE NOT NULL, 
    DELETE_FLAG        CHAR(1)         DEFAULT 'N' NOT NULL, 
    CONSTRAINT CODE_ITEM_PK PRIMARY KEY (SEQ)
)
/

CREATE SEQUENCE CODE_ITEM_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER CODE_ITEM_AI_TRG
BEFORE INSERT ON CODE_ITEM 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT CODE_ITEM_SEQ.NEXTVAL
    INTO :NEW.SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER CODE_ITEM_AI_TRG;
/

--DROP SEQUENCE CODE_ITEM_SEQ;
/

COMMENT ON TABLE CODE_ITEM IS '코드아이템'
/

COMMENT ON COLUMN CODE_ITEM.SEQ IS 'CODE SLAVE'
/

COMMENT ON COLUMN CODE_ITEM.CODE_SEQ IS '코드 SEQ'
/

COMMENT ON COLUMN CODE_ITEM.NAME IS '코드아이템 명'
/

COMMENT ON COLUMN CODE_ITEM.CREATE_USERID IS '작성자'
/

COMMENT ON COLUMN CODE_ITEM.CREATE_DATETIME IS '작성시간'
/

COMMENT ON COLUMN CODE_ITEM.UPDATE_USERID IS '수정자'
/

COMMENT ON COLUMN CODE_ITEM.UPDATE_DATETIME IS '수정시간'
/

COMMENT ON COLUMN CODE_ITEM.DELETE_FLAG IS '삭제여부'
/

ALTER TABLE CODE_ITEM
    ADD CONSTRAINT FK_CODE_ITEM_CODE_SEQ_CODE_SEQ FOREIGN KEY (CODE_SEQ)
        REFERENCES CODE (SEQ)
/


-- CODE Table Create SQL
CREATE TABLE MEMBER
(
    SEQ                NUMBER           NOT NULL, 
    USER_NAME          VARCHAR2(20)     NULL, 
    USER_ID            VARCHAR2(20)     NOT NULL, 
    PW                 VARCHAR2(25)     NOT NULL, 
    EMAIL              VARCHAR2(40)     NOT NULL, 
    USER_PHONE         VARCHAR2(25)     NULL, 
    ADDRESS1           VARCHAR2(100)    NULL, 
    ADDRESS2           VARCHAR2(100)    NULL, 
    CREATE_USERID      VARCHAR2(20)     NOT NULL, 
    CREATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    UPDATE_USERID      VARCHAR2(20)     NOT NULL, 
    UPDATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    DELETE_FLAG        CHAR(1)          DEFAULT 'N' NOT NULL, 
    ACCESS_LEVEL       NUMBER           DEFAULT 1 NOT NULL, 
    CONSTRAINT MEMBER_PK PRIMARY KEY (SEQ)
)
/

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER MEMBER_AI_TRG
BEFORE INSERT ON MEMBER 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT MEMBER_SEQ.NEXTVAL
    INTO :NEW.SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER MEMBER_AI_TRG;
/

--DROP SEQUENCE MEMBER_SEQ;
/

COMMENT ON TABLE MEMBER IS '회원정보'
/

COMMENT ON COLUMN MEMBER.SEQ IS '번호'
/

COMMENT ON COLUMN MEMBER.USER_NAME IS '이름'
/

COMMENT ON COLUMN MEMBER.USER_ID IS '아이디'
/

COMMENT ON COLUMN MEMBER.PW IS '비밀번호'
/

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일'
/

COMMENT ON COLUMN MEMBER.USER_PHONE IS '연락처'
/

COMMENT ON COLUMN MEMBER.ADDRESS1 IS '주소'
/

COMMENT ON COLUMN MEMBER.ADDRESS2 IS '주소2'
/

COMMENT ON COLUMN MEMBER.CREATE_USERID IS '작성자'
/

COMMENT ON COLUMN MEMBER.CREATE_DATETIME IS '작성시간'
/

COMMENT ON COLUMN MEMBER.UPDATE_USERID IS '수정자'
/

COMMENT ON COLUMN MEMBER.UPDATE_DATETIME IS '수정시간'
/

COMMENT ON COLUMN MEMBER.DELETE_FLAG IS '삭제여부'
/

COMMENT ON COLUMN MEMBER.ACCESS_LEVEL IS '관리자 0, 기본 1'
/

ALTER TABLE MEMBER
    ADD CONSTRAINT UC_USER_ID UNIQUE (USER_ID)
/


-- CODE Table Create SQL
CREATE TABLE REPLY
(
    R_SEQ              NUMBER           NOT NULL, 
    SEQ                NUMBER           NOT NULL, 
    CREATE_USERID      VARCHAR2(20)     NOT NULL, 
    CONTENT            VARCHAR2(500)    NOT NULL, 
    CREATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    UPDATE_DATETIME    DATE             DEFAULT SYSDATE NOT NULL, 
    CONSTRAINT REPLY_PK PRIMARY KEY (R_SEQ)
)
/

CREATE SEQUENCE REPLY_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER REPLY_AI_TRG
BEFORE INSERT ON REPLY 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT REPLY_SEQ.NEXTVAL
    INTO :NEW.R_SEQ
    FROM DUAL;
END;
/

--DROP TRIGGER REPLY_AI_TRG;
/

--DROP SEQUENCE REPLY_SEQ;
/

COMMENT ON TABLE REPLY IS '댓글'
/

COMMENT ON COLUMN REPLY.R_SEQ IS '댓글번호'
/

COMMENT ON COLUMN REPLY.SEQ IS '글번호'
/

COMMENT ON COLUMN REPLY.CREATE_USERID IS '작성자'
/

COMMENT ON COLUMN REPLY.CONTENT IS '내용'
/

COMMENT ON COLUMN REPLY.CREATE_DATETIME IS '작성시간'
/

COMMENT ON COLUMN REPLY.UPDATE_DATETIME IS '수정시간'
/

ALTER TABLE REPLY
    ADD CONSTRAINT FK_REPLY_SEQ_BOARD_SEQ FOREIGN KEY (SEQ)
        REFERENCES BOARD (SEQ)
/


